name: CI Base Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        app: ['basket-api', 'plant-api']
    name: Unit Test - ${{ matrix.app }} - Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '${{ matrix.app }}/package-lock.json'
      - name: Run tests
        working-directory: ./${{ matrix.app }}
        run: |
          npm ci
          npm run test

  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        app: [ 'basket-api', 'plant-api' ]
    name: Audit - ${{ matrix.app }} - Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '${{ matrix.app }}/package-lock.json'
      - name: Run npm audit
        working-directory: ./${{ matrix.app }}
        run: |
          npm ci
          npm audit

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        app: [ 'basket-api', 'plant-api' ]
    name: Coverage - ${{ matrix.app }} - Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '${{ matrix.app }}/package-lock.json'
      - name: Run coverage
        working-directory: ./${{ matrix.app }}
        run: |
          npm ci
          npm run coverage

  deploy:
    runs-on: ubuntu-latest
    needs: [ unit-test, audit, coverage ]
    steps:
      - uses: actions/checkout@v2
      - run: echo "No Deploy Fridays"