name: CI PM2 Orchestration Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-orchestration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        app: [ 'basket-api', 'plant-api' ]
    name: Orchestration Test - ${{ matrix.app }} - Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '${{ matrix.app }}/package-lock.json'
      - name: Run tests
        run: |
          sh orchestration/pm2/start.sh
          sleep 30
          sh test/${{ matrix.app }}-test.sh
          sh orchestration/pm2/stop.sh